# Q1

In [4]:
import numpy as np
np.__version__

'1.19.2'

# Q2

In [5]:
import pandas as pd
pd.__version__

'1.1.3'

# Q3

In [172]:
df = pd.read_csv("data.csv")

In [173]:
df_bmw = df[
    df['Make'] == 'BMW'
]

In [174]:
df_bmw.MSRP.mean()

61546.76347305389

# Q4 

In [170]:
df_2015 = df[
    df['Year'] >= 2015
]

In [167]:
df_2015

Make       Model  Year                Engine Fuel Type  Engine HP  \
32     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41      BMW    2 Series  2016     premium unleaded (required)      240.0   
42      BMW    2 Series  2016     premium unleaded (required)      240.0   
...     ...         ...   ...                             ...        ...   
11879   GMC       Yukon  2017        flex-fuel (unleaded/E85)      355.0   
11880   GMC       Yukon  2017        flex-fuel (unleaded/E85)      355.0   
11900   BMW          Z4  2016     premium unleaded (required)      300.0   
11901   BMW          Z4  2016     premium unleaded (required)      240.0   
11902   BMW          Z4  2016     premium unleaded (required)      335.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32                  4.0            MANUAL  rear wheel drive              2.0   
33                  4.0            MANUAL  rear wheel drive              2.0   
34                  4.0            MANUAL  rear wheel drive              2.0   
41                  4.0         AUTOMATIC  rear wheel drive              2.0   
42                  4.0         AUTOMATIC  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11879               8.0         AUTOMATIC  four wheel drive              4.0   
11880               8.0         AUTOMATIC  rear wheel drive              4.0   
11900               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   

               Market Category Vehicle Size Vehicle Style  highway MPG  \
32                 Performance      Compact   Convertible           35   
33                 Performance      Compact   Convertible           35   
34                 Performance      Compact   Convertible           35   
41          Luxury,Performance      Compact         Coupe           35   
42                      Luxury      Compact   Convertible           34   
...                        ...          ...           ...          ...   
11879    Flex Fuel,Performance        Large       4dr SUV           22   
11880    Flex Fuel,Performance        Large       4dr SUV           23   
11900  Luxury,High-Performance      Compact   Convertible           24   
11901       Luxury,Performance      Compact   Convertible           34   
11902  Luxury,High-Performance      Compact   Convertible           24   

       city mpg  Popularity   MSRP  
32           26         819  27495  
33           26         819  24995  
34           26         819  28195  
41           23        3916  32850  
42           23        3916  38650  
...         ...         ...    ...  
11879        16         549  60315  
11880        16         549  48530  
11900        17        3916  57500  
11901        22        3916  49700  
11902        17        3916  66350  

[3825 rows x 16 columns]

In [171]:
df_2015['Engine HP'].isnull().sum()

51

# Q5

In [112]:
df['Engine HP'].mean()

249.38607007176023

In [116]:
df_fillna = df['Engine HP'].fillna(value=249.38607007176023)

In [118]:
df_fillna.isnull().sum()

0

In [119]:
df_fillna.mean()

249.38607007176

# Q6

In [121]:
df_RR = df[
    df['Make'] == 'Rolls-Royce'
]

In [125]:
df_RR_filter = df_RR[["Engine HP", "Engine Cylinders", "highway MPG"]]

In [149]:
df_RR_filter_drop = df_RR_filter.drop_duplicates()
df_RR_filter_drop

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [150]:
X = df_RR_filter_drop.values

In [151]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [157]:
XT = X.T
XT

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [158]:
XTX = XT.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [160]:
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [161]:
XTXinv.sum()

0.032212320677486195

# Q7

In [140]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [162]:
y = np.array(y)
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [163]:
X_new = XTXinv.dot(XT)
X_new

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [165]:
w = X_new.dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])