# Q1

In [4]:
import numpy as np
np.__version__

'1.19.2'

# Q2

In [5]:
import pandas as pd
pd.__version__

'1.1.3'

In [7]:
np.random.seed(2)
100 * np.random.randn(5,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [8]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [10]:
a * 2

array([0, 2, 4, 6, 8])

In [11]:
b = 2 * a

In [12]:
b

array([0, 2, 4, 6, 8])

In [13]:
a+b

array([ 0,  3,  6,  9, 12])

In [14]:
a >= 2

array([False, False,  True,  True,  True])

In [15]:
a > b

array([False, False, False, False, False])

In [17]:
a[a < b]

array([1, 2, 3, 4])

In [18]:
a.min()

0

In [19]:
a.max()

4

In [20]:
a.sum()

10

In [21]:
a.mean()

2.0

In [22]:
a.std()

1.4142135623730951

In [24]:
u = np.array([2, 4, 5, 6])

In [25]:
v = np.array([1, 0, 0, 2])

In [26]:
u + v

array([3, 4, 5, 8])

In [27]:
u * v

array([ 2,  0,  0, 12])

In [33]:
def vector_vector_mult(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
        
    return result

In [34]:
vector_vector_mult(u, v)

14.0

In [35]:
u.dot(v)

14

In [36]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [93]:
df = pd.read_csv("data.csv")
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [44]:
df.Make

0            BMW
1            BMW
2            BMW
3            BMW
4            BMW
          ...   
11909      Acura
11910      Acura
11911      Acura
11912      Acura
11913    Lincoln
Name: Make, Length: 11914, dtype: object

In [46]:
df["Engine HP"]

0        335.0
1        300.0
2        300.0
3        230.0
4        230.0
         ...  
11909    300.0
11910    300.0
11911    300.0
11912    300.0
11913    221.0
Name: Engine HP, Length: 11914, dtype: float64

In [49]:
df[["Make", "Model", "MSRP"]]

Make       Model   MSRP
0          BMW  1 Series M  46135
1          BMW    1 Series  40650
2          BMW    1 Series  36350
3          BMW    1 Series  29450
4          BMW    1 Series  34500
...        ...         ...    ...
11909    Acura         ZDX  46120
11910    Acura         ZDX  56670
11911    Acura         ZDX  50620
11912    Acura         ZDX  50920
11913  Lincoln      Zephyr  28995

[11914 rows x 3 columns]

In [51]:
df.index

RangeIndex(start=0, stop=11914, step=1)

In [52]:
df.Make.index

RangeIndex(start=0, stop=11914, step=1)

In [55]:
df.loc[[1,2]]

Make     Model  Year             Engine Fuel Type  Engine HP  \
1  BMW  1 Series  2011  premium unleaded (required)      300.0   
2  BMW  1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   

           Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
1       Luxury,Performance      Compact   Convertible           28        19   
2  Luxury,High-Performance      Compact         Coupe           28        20   

   Popularity   MSRP  
1        3916  40650  
2        3916  36350

In [56]:
df.iloc[1]

Make                                         BMW
Model                                   1 Series
Year                                        2011
Engine Fuel Type     premium unleaded (required)
Engine HP                                    300
Engine Cylinders                               6
Transmission Type                         MANUAL
Driven_Wheels                   rear wheel drive
Number of Doors                                2
Market Category               Luxury,Performance
Vehicle Size                             Compact
Vehicle Style                        Convertible
highway MPG                                   28
city mpg                                      19
Popularity                                  3916
MSRP                                       40650
Name: 1, dtype: object

In [58]:
df["Engine HP"] / 100

0        3.35
1        3.00
2        3.00
3        2.30
4        2.30
         ... 
11909    3.00
11910    3.00
11911    3.00
11912    3.00
11913    2.21
Name: Engine HP, Length: 11914, dtype: float64

In [59]:
df["Year"] >= 2015

0        False
1        False
2        False
3        False
4        False
         ...  
11909    False
11910    False
11911    False
11912    False
11913    False
Name: Year, Length: 11914, dtype: bool

In [61]:
df[
    (df["Year"] >= 2015) & (df["Make"] == "Nissan")
]

Make   Model  Year             Engine Fuel Type  Engine HP  \
307    Nissan    370Z  2015  premium unleaded (required)      350.0   
308    Nissan    370Z  2015  premium unleaded (required)      332.0   
309    Nissan    370Z  2015  premium unleaded (required)      332.0   
310    Nissan    370Z  2015  premium unleaded (required)      332.0   
311    Nissan    370Z  2015  premium unleaded (required)      332.0   
...       ...     ...   ...                          ...        ...   
11760  Nissan  Xterra  2015             regular unleaded      261.0   
11761  Nissan  Xterra  2015             regular unleaded      261.0   
11762  Nissan  Xterra  2015             regular unleaded      261.0   
11763  Nissan  Xterra  2015             regular unleaded      261.0   
11764  Nissan  Xterra  2015             regular unleaded      261.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
307                 6.0         AUTOMATIC  rear wheel drive              2.0   
308                 6.0            MANUAL  rear wheel drive              2.0   
309                 6.0            MANUAL  rear wheel drive              2.0   
310                 6.0         AUTOMATIC  rear wheel drive              2.0   
311                 6.0         AUTOMATIC  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11760               6.0         AUTOMATIC  four wheel drive              4.0   
11761               6.0            MANUAL  four wheel drive              4.0   
11762               6.0         AUTOMATIC  rear wheel drive              4.0   
11763               6.0         AUTOMATIC  four wheel drive              4.0   
11764               6.0         AUTOMATIC  rear wheel drive              4.0   

                      Market Category Vehicle Size Vehicle Style  highway MPG  \
307    Factory Tuner,High-Performance      Compact         Coupe           26   
308                  High-Performance      Compact   Convertible           24   
309                  High-Performance      Compact         Coupe           26   
310                  High-Performance      Compact   Convertible           25   
311                  High-Performance      Compact         Coupe           26   
...                               ...          ...           ...          ...   
11760                             NaN      Midsize       4dr SUV           20   
11761                             NaN      Midsize       4dr SUV           20   
11762                             NaN      Midsize       4dr SUV           22   
11763                             NaN      Midsize       4dr SUV           20   
11764                             NaN      Midsize       4dr SUV           22   

       city mpg  Popularity   MSRP  
307          19        2009  46790  
308          17        2009  48100  
309          18        2009  29990  
310          18        2009  41820  
311          19        2009  31290  
...         ...         ...    ...  
11760        15        2009  25710  
11761        15        2009  30590  
11762        16        2009  23660  
11763        15        2009  31640  
11764        16        2009  25670  

[391 rows x 16 columns]

In [63]:
'STRr'.lower()

'strr'

In [65]:
'test test'.replace(' ','_')

'test_test'

In [72]:
df["Vehicle Style"] = df["Vehicle Style"].str.replace(' ','_').str.lower()
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         coupe   
1                     Luxury,Performance      Compact   convertible   
2                Luxury,High-Performance      Compact         coupe   
3                     Luxury,Performance      Compact         coupe   
4                                 Luxury      Compact   convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

# Q3

In [100]:
df_bmw = df[
    df['Make'] == 'BMW'
]

In [101]:
df_bmw.MSRP.mean()

61546.76347305389

# Q4 

In [170]:
df_2015 = df[
    df['Year'] >= 2015
]

In [167]:
df_2015

Make       Model  Year                Engine Fuel Type  Engine HP  \
32     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41      BMW    2 Series  2016     premium unleaded (required)      240.0   
42      BMW    2 Series  2016     premium unleaded (required)      240.0   
...     ...         ...   ...                             ...        ...   
11879   GMC       Yukon  2017        flex-fuel (unleaded/E85)      355.0   
11880   GMC       Yukon  2017        flex-fuel (unleaded/E85)      355.0   
11900   BMW          Z4  2016     premium unleaded (required)      300.0   
11901   BMW          Z4  2016     premium unleaded (required)      240.0   
11902   BMW          Z4  2016     premium unleaded (required)      335.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32                  4.0            MANUAL  rear wheel drive              2.0   
33                  4.0            MANUAL  rear wheel drive              2.0   
34                  4.0            MANUAL  rear wheel drive              2.0   
41                  4.0         AUTOMATIC  rear wheel drive              2.0   
42                  4.0         AUTOMATIC  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11879               8.0         AUTOMATIC  four wheel drive              4.0   
11880               8.0         AUTOMATIC  rear wheel drive              4.0   
11900               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   

               Market Category Vehicle Size Vehicle Style  highway MPG  \
32                 Performance      Compact   Convertible           35   
33                 Performance      Compact   Convertible           35   
34                 Performance      Compact   Convertible           35   
41          Luxury,Performance      Compact         Coupe           35   
42                      Luxury      Compact   Convertible           34   
...                        ...          ...           ...          ...   
11879    Flex Fuel,Performance        Large       4dr SUV           22   
11880    Flex Fuel,Performance        Large       4dr SUV           23   
11900  Luxury,High-Performance      Compact   Convertible           24   
11901       Luxury,Performance      Compact   Convertible           34   
11902  Luxury,High-Performance      Compact   Convertible           24   

       city mpg  Popularity   MSRP  
32           26         819  27495  
33           26         819  24995  
34           26         819  28195  
41           23        3916  32850  
42           23        3916  38650  
...         ...         ...    ...  
11879        16         549  60315  
11880        16         549  48530  
11900        17        3916  57500  
11901        22        3916  49700  
11902        17        3916  66350  

[3825 rows x 16 columns]

In [171]:
df_2015['Engine HP'].isnull().sum()

51

# Q5

In [112]:
df['Engine HP'].mean()

249.38607007176023

In [116]:
df_fillna = df['Engine HP'].fillna(value=249.38607007176023)

In [118]:
df_fillna.isnull().sum()

0

In [119]:
df_fillna.mean()

249.38607007176

In [121]:
df_RR = df[
    df['Make'] == 'Rolls-Royce'
]

In [125]:
df_RR_filter = df_RR[["Engine HP", "Engine Cylinders", "highway MPG"]]

In [149]:
df_RR_filter_drop = df_RR_filter.drop_duplicates()
df_RR_filter_drop

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [150]:
X = df_RR_filter_drop.values

In [151]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [157]:
XT = X.T
XT

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [158]:
XTX = XT.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [160]:
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [161]:
XTXinv.sum()

0.032212320677486195

# Q7

In [140]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [162]:
y = np.array(y)
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [163]:
X_new = XTXinv.dot(XT)
X_new

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [165]:
w = X_new.dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])